apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # selector : 어떤 pod에 서비스를 사용할 지 선택.
  # Pod의 labels를 통해 접근
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort